version: '3'
services:
    ### Application 
    app:
        depends_on:
            - db
        build:
            context: ./
            dockerfile: docker/app/Dockerfile
        working_dir: /app
        restart: always
        volumes:
            - ./:/app

    ####  Nginx
    web:
        build:
            context: ./
            dockerfile: docker/nginx/Dockerfile
        working_dir: /app
        restart: always
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/request_trace.js:/etc/nginx/request_trace.js
            - ./docker/nginx/request_trace.conf:/etc/nginx/request_trace.conf
        links:
            - app
        ports:
            - "80:80"
    ### Database
    db:
        image: mysql:8
        restart: always
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: current-account
            MYSQL_USER: current-account
            MYSQL_PASSWORD: secret

volumes:
    db_data: {}